### ISSUE TITLE
issue while training 

### ISSUE THREAD

**Issue by ghost** [soumyaiitkgp/Custom_MaskRCNN#11]

**Comment by jcedrickm** [comment]
I encounter this error please help
Traceback (most recent call last):
  File "custom.py", line 385, in <module>
    train(model)
  File "custom.py", line 200, in train
    dataset_train.load_custom(args.dataset, "train")
  File "custom.py", line 114, in load_custom
    annotations = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\..\\Custom_MaskRCNN\\samples\\custom\\dataset\\train\\via_region_data.json'
